/**
 * Node adapter（栈 A/A2/B）：NestJS + Prisma。
 *
 * 生成（<out>/api 下）：
 *   - prisma/schema.prisma          实体模型 + AdminUser（闸门账号）
 *   - prisma/seed.ts                seedAdmin + 各实体种子数据
 *   - src/main.ts                   Nest 引导（全局前缀 /api、CORS、端口）
 *   - src/app.module.ts             模块汇总（含全局 JwtGuard）
 *   - src/common/prisma.service.ts  PrismaService
 *   - src/auth/*                    JWT 登录（seedAdmin 校验）+ 守卫
 *   - src/resources/<route>/*       每资源 controller/service/module
 *   - src/dashboard/*               stats/charts（存在 dashboard 屏时）
 *   - package.json / tsconfig.json / .env
 */
import { resolve } from "node:path";
import { writeFileSafe, resolveDbConnection, cap } from "./util.mjs";

const Q = (s) => JSON.stringify(String(s ?? ""));
const camelize = (s) => s.charAt(0).toLowerCase() + s.slice(1);

/** spec 字段类型 → TS 类型 */
function toTsType(t) {
  switch (t) {
    case "Integer":
    case "Float":
    case "Decimal":
      return "number";
    case "Boolean":
      return "boolean";
    default:
      return "string";
  }
}

export function generateNestPrisma(ctx) {
  const { spec, stack, entities, outDir } = ctx;
  const apiDir = resolve(outDir, "api");
  const files = [];
  const w = (rel, content) => {
    writeFileSafe(resolve(apiDir, rel), content);
    files.push(`api/${rel}`);
  };

  genSchema();
  genSeed();
  genMain();
  genCommon();
  genAuth();
  for (const e of entities) genResource(e);
  const hasDash = (spec.screens || []).some((s) => s.type === "dashboard");
  if (hasDash) genDashboard();
  genAppModule(hasDash);
  genProjectFiles();

  return { files };

  // ———————————— 各部分生成 ————————————

  function genSchema() {
    const provider = stack.database === "mysql" ? "mysql" : "postgresql";
    const models = entities
      .map((e) => {
        const fields = e.fields
          .map((f) => `  ${f.name}  ${toPrisma(f.type)}`)
          .join("\n");
        return `model ${e.name} {
  id        Int      @id @default(autoincrement())
${fields}
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@map("${e.table}")
}`;
      })
      .join("\n\n");
    const schema = `// generated by scripts/gen-backend.mjs — project: ${spec.slug}
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${provider}"
  url      = env("DATABASE_URL")
}

model AdminUser {
  id        Int      @id @default(autoincrement())
  email     String   @unique
  username  String   @unique
  password  String
  name      String   @default("")
  status    String   @default("active")
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@map("admin_users")
}

${models}
`;
    w("prisma/schema.prisma", schema);
  }

  function genSeed() {
    const admin = spec.seedAdmin || { email: "", username: "", password: "" };
    const blocks = entities
      .map((e) => {
        const rows =
          e.seedRows?.length
            ? e.seedRows
            : Array.from({ length: e.seedCount ?? 6 }, (_, i) =>
                Object.fromEntries(
                  e.fields.map((f) => [f.name, `${e.name}示例${i + 1}`]),
                ),
              );
        const data = rows
          .map(
            (r) =>
              `      { ${e.fields.map((f) => `${f.name}: ${Q(r[f.name])}`).join(", ")} },`,
          )
          .join("\n");
        return `  await prisma.${camelize(e.name)}.createMany({ data: [
${data}
  ], skipDuplicates: true });`;
      })
      .join("\n\n");
    const seed = `// generated by scripts/gen-backend.mjs — project: ${spec.slug}
import { PrismaClient } from "@prisma/client";
import * as bcrypt from "bcrypt";

const prisma = new PrismaClient();

const seedAdmin = ${JSON.stringify(admin, null, 2)};

async function main() {
  await prisma.adminUser.upsert({
    where: { email: seedAdmin.email },
    update: {},
    create: {
      email: seedAdmin.email,
      username: seedAdmin.username || seedAdmin.email,
      password: await bcrypt.hash(seedAdmin.password, 10),
      name: "管理员",
      status: "active",
    },
  });

${blocks}

  console.log("seed done");
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
`;
    w("prisma/seed.ts", seed);
  }

  function genMain() {
    w(
      "src/main.ts",
      `// generated by scripts/gen-backend.mjs — project: ${spec.slug}
import "reflect-metadata";
import { NestFactory } from "@nestjs/core";
import { AppModule } from "./app.module";

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.setGlobalPrefix("api");
  app.enableCors({ origin: ["http://localhost:5173", "http://127.0.0.1:5173"] });
  const port = Number(process.env.API_PORT || 3001);
  await app.listen(port);
  console.log("api listening on", port);
}
bootstrap();
`,
    );
  }

  function genCommon() {
    w(
      "src/common/prisma.service.ts",
      `// generated by scripts/gen-backend.mjs
import { Injectable, OnModuleDestroy, OnModuleInit } from "@nestjs/common";
import { PrismaClient } from "@prisma/client";

@Injectable()
export class PrismaService extends PrismaClient implements OnModuleInit, OnModuleDestroy {
  async onModuleInit() {
    await this.$connect();
  }
  async onModuleDestroy() {
    await this.$disconnect();
  }
}
`,
    );
    w(
      "src/common/jwt.guard.ts",
      `// generated by scripts/gen-backend.mjs
import { CanActivate, ExecutionContext, Injectable, UnauthorizedException } from "@nestjs/common";
import { JwtService } from "@nestjs/jwt";

@Injectable()
export class JwtGuard implements CanActivate {
  constructor(private jwt: JwtService) {}

  canActivate(context: ExecutionContext): boolean {
    const req = context.switchToHttp().getRequest();
    const header = req.headers.authorization || "";
    const token = header.startsWith("Bearer ") ? header.slice(7) : null;
    if (!token) throw new UnauthorizedException();
    try {
      req.user = this.jwt.verify(token);
      return true;
    } catch {
      throw new UnauthorizedException();
    }
  }
}
`,
    );
  }

  function genAuth() {
    w(
      "src/auth/auth.service.ts",
      `// generated by scripts/gen-backend.mjs
import { Injectable, UnauthorizedException, ForbiddenException } from "@nestjs/common";
import { PrismaService } from "../common/prisma.service";
import { JwtService } from "@nestjs/jwt";
import * as bcrypt from "bcrypt";

@Injectable()
export class AuthService {
  constructor(
    private prisma: PrismaService,
    private jwt: JwtService,
  ) {}

  async login(username: string, password: string) {
    const user =
      (await this.prisma.adminUser.findUnique({ where: { username } })) ||
      (await this.prisma.adminUser.findUnique({ where: { email: username } }));
    if (!user || !(await bcrypt.compare(password, user.password))) {
      throw new UnauthorizedException("用户名或密码错误");
    }
    if (user.status !== "active") {
      throw new ForbiddenException("账号已禁用");
    }
    const payload = { sub: user.username, username: user.username, name: user.name };
    return { token: this.jwt.sign(payload), user: { username: user.username, name: user.name } };
  }
}
`,
    );
    w(
      "src/auth/auth.controller.ts",
      `// generated by scripts/gen-backend.mjs
import { Body, Controller, Post } from "@nestjs/common";
import { AuthService } from "./auth.service";

@Controller("auth")
export class AuthController {
  constructor(private svc: AuthService) {}

  @Post("login")
  login(@Body() body: { username?: string; email?: string; password: string }) {
    return this.svc.login(body.username || body.email || "", body.password);
  }
}
`,
    );
    w(
      "src/auth/auth.module.ts",
      `// generated by scripts/gen-backend.mjs
import { Module } from "@nestjs/common";
import { JwtModule } from "@nestjs/jwt";
import { AuthController } from "./auth.controller";
import { AuthService } from "./auth.service";
import { PrismaService } from "../common/prisma.service";

@Module({
  imports: [
    JwtModule.register({
      secret: process.env.JWT_SECRET || "change-me-in-dev",
      signOptions: { expiresIn: process.env.JWT_EXPIRES_IN || "7d" },
    }),
  ],
  controllers: [AuthController],
  providers: [AuthService, PrismaService],
})
export class AuthModule {}
`,
    );
  }

  function genResource(e) {
    const C = e.name;
    const dir = `src/resources/${e.route}`;
    const model = camelize(C);
    const inputType = `${C}Input`;
    const tsFields = e.fields
      .map((f) => `  ${f.name}?: ${toTsType(f.type)};`)
      .join("\n");

    w(
      `${dir}/${C.toLowerCase()}.dto.ts`,
      `// generated by scripts/gen-backend.mjs
export interface ${inputType} {
${tsFields}
}
`,
    );
    w(
      `${dir}/${C.toLowerCase()}.service.ts`,
      `// generated by scripts/gen-backend.mjs
import { Injectable, NotFoundException } from "@nestjs/common";
import { PrismaService } from "../../common/prisma.service";
import { ${inputType} } from "./${C.toLowerCase()}.dto";

@Injectable()
export class ${C}Service {
  constructor(private prisma: PrismaService) {}

  list() {
    return this.prisma.${model}.findMany({ orderBy: { id: "asc" } });
  }

  async get(id: number) {
    const row = await this.prisma.${model}.findUnique({ where: { id } });
    if (!row) throw new NotFoundException();
    return row;
  }

  create(data: ${inputType}) {
    return this.prisma.${model}.create({ data });
  }

  async update(id: number, data: Partial<${inputType}>) {
    await this.get(id);
    return this.prisma.${model}.update({ where: { id }, data });
  }

  async remove(id: number) {
    await this.get(id);
    await this.prisma.${model}.delete({ where: { id } });
    return { ok: true };
  }
}
`,
    );
    w(
      `${dir}/${C.toLowerCase()}.controller.ts`,
      `// generated by scripts/gen-backend.mjs
import { Body, Controller, Delete, Get, Param, ParseIntPipe, Patch, Post } from "@nestjs/common";
import { ${C}Service } from "./${C.toLowerCase()}.service";
import { ${inputType} } from "./${C.toLowerCase()}.dto";

@Controller("${e.route}")
export class ${C}Controller {
  constructor(private svc: ${C}Service) {}

  @Get()
  list() {
    return this.svc.list();
  }

  @Get(":id")
  get(@Param("id", ParseIntPipe) id: number) {
    return this.svc.get(id);
  }

  @Post()
  create(@Body() body: ${inputType}) {
    return this.svc.create(body);
  }

  @Patch(":id")
  update(@Param("id", ParseIntPipe) id: number, @Body() body: Partial<${inputType}>) {
    return this.svc.update(id, body);
  }

  @Delete(":id")
  remove(@Param("id", ParseIntPipe) id: number) {
    return this.svc.remove(id);
  }
}
`,
    );
    w(
      `${dir}/${C.toLowerCase()}.module.ts`,
      `// generated by scripts/gen-backend.mjs
import { Module } from "@nestjs/common";
import { ${C}Controller } from "./${C.toLowerCase()}.controller";
import { ${C}Service } from "./${C.toLowerCase()}.service";

@Module({
  controllers: [${C}Controller],
  providers: [${C}Service],
})
export class ${C}Module {}
`,
    );
  }

  function genDashboard() {
    const dash = (spec.screens || []).find((s) => s.type === "dashboard");
    const statKeys = (dash?.stats || []).map((s) => s.key).filter(Boolean);
    const statLines = statKeys.length
      ? statKeys.map((k) => `      ${JSON.stringify(k)}: 0,`).join("\n")
      : `      total: 0,`;
    w(
      "src/dashboard/dashboard.controller.ts",
      `// generated by scripts/gen-backend.mjs
import { Controller, Get } from "@nestjs/common";
import { PrismaService } from "../common/prisma.service";

@Controller("dashboard")
export class DashboardController {
  constructor(private prisma: PrismaService) {}

  @Get("stats")
  async stats() {
    return {
${statLines}
    };
  }

  @Get("charts")
  charts() {
    // 图表数据：闸门后按 screen.stats/visual-ir 补充聚合逻辑
    return { labels: [], values: [] };
  }
}
`,
    );
    w(
      "src/dashboard/dashboard.module.ts",
      `// generated by scripts/gen-backend.mjs
import { Module } from "@nestjs/common";
import { DashboardController } from "./dashboard.controller";
import { PrismaService } from "../common/prisma.service";

@Module({
  controllers: [DashboardController],
  providers: [PrismaService],
})
export class DashboardModule {}
`,
    );
  }

  function genAppModule(hasDash) {
    const imports = entities
      .map(
        (e) =>
          `import { ${e.name}Module } from "./resources/${e.route}/${e.name.toLowerCase()}.module";`,
      )
      .join("\n");
    const modNames = [
      "AuthModule",
      ...entities.map((e) => `${e.name}Module`),
      ...(hasDash ? ["DashboardModule"] : []),
    ];
    w(
      "src/app.module.ts",
      `// generated by scripts/gen-backend.mjs — project: ${spec.slug}
import { Module } from "@nestjs/common";
import { APP_GUARD } from "@nestjs/core";
import { JwtModule } from "@nestjs/jwt";
${imports}${hasDash ? `\nimport { DashboardModule } from "./dashboard/dashboard.module";` : ""}
import { AuthModule } from "./auth/auth.module";
import { JwtGuard } from "./common/jwt.guard";
import { PrismaService } from "./common/prisma.service";

@Module({
  imports: [
    JwtModule.register({
      secret: process.env.JWT_SECRET || "change-me-in-dev",
      signOptions: { expiresIn: process.env.JWT_EXPIRES_IN || "7d" },
    }),
    AuthModule,
${entities.map((e) => `    ${e.name}Module,`).join("\n")}${hasDash ? "\n    DashboardModule," : ""}
  ],
  providers: [
    PrismaService,
    { provide: APP_GUARD, useClass: JwtGuard },
  ],
})
export class AppModule {}
`,
    );
  }

  function genProjectFiles() {
    w(
      "package.json",
      JSON.stringify(
        {
          name: `${spec.slug}-api`,
          version: "1.0.0",
          private: true,
          scripts: {
            start: "node dist/main",
            "start:dev": "nest start --watch",
            build: "prisma generate && tsc -p tsconfig.json",
            "prisma:generate": "prisma generate",
            migrate: "prisma migrate dev",
            "prisma:seed": "ts-node prisma/seed.ts",
            "db:reset": "prisma migrate reset --force",
          },
          dependencies: {
            "@nestjs/common": "^10.4.0",
            "@nestjs/core": "^10.4.0",
            "@nestjs/jwt": "^10.2.0",
            "@nestjs/platform-express": "^10.4.0",
            "@prisma/client": "^5.22.0",
            bcrypt: "^5.1.1",
            "reflect-metadata": "^0.2.2",
            rxjs: "^7.8.1",
          },
          devDependencies: {
            "@nestjs/cli": "^10.4.0",
            "@types/bcrypt": "^5.0.2",
            "@types/node": "^22.0.0",
            prisma: "^5.22.0",
            "ts-node": "^10.9.2",
            typescript: "^5.6.0",
          },
          prisma: { seed: "ts-node prisma/seed.ts" },
        },
        null,
        2,
      ),
    );
    w(
      "tsconfig.json",
      JSON.stringify(
        {
          compilerOptions: {
            target: "ES2022",
            module: "commonjs",
            moduleResolution: "node",
            emitDecoratorMetadata: true,
            experimentalDecorators: true,
            outDir: "dist",
            strict: true,
            skipLibCheck: true,
            esModuleInterop: true,
          },
          include: ["src"],
        },
        null,
        2,
      ),
    );
    const { url } = resolveDbConnection(stack.database);
    w(
      ".env",
      `# generated by scripts/gen-backend.mjs（连接串取自仓库根 .env 预置）
DATABASE_URL=${url}
JWT_SECRET=${process.env.JWT_SECRET || "change-me-in-dev"}
JWT_EXPIRES_IN=${process.env.JWT_EXPIRES_IN || "7d"}
API_PORT=3001
`,
    );
  }
}

/** spec 字段类型 → Prisma 列定义 */
function toPrisma(t) {
  switch (t) {
    case "Integer":
      return "Int?";
    case "Float":
    case "Decimal":
      return "Float?";
    case "Boolean":
      return "Boolean?";
    case "DateTime":
      return "DateTime?";
    default:
      return "String?";
  }
}