#!/usr/bin/env node
/**
 * 拼接 Figma 插件单文件 code.js：
 *   svgs.js（SVG 数据） + logic.part.js（emoji 命令） + charts.part.js（图表组件化命令） + dispatch.part.js（命令分发）
 * Figma 插件主线程沙箱没有 window，也没有模块加载机制，
 * 所以必须把数据与逻辑内联进同一个文件。
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)));
const svgSrc = readFileSync(resolve(root, 'svgs.js'), 'utf8');
const logicSrc = readFileSync(resolve(root, 'src/logic.part.js'), 'utf8');
const chartsSrc = readFileSync(resolve(root, 'src/charts.part.js'), 'utf8');
const dispatchSrc = readFileSync(resolve(root, 'src/dispatch.part.js'), 'utf8');

// svgs.js 原为浏览器环境写法：window.SVG_DATA = {...};
// 插件主线程无 window，改为直接声明常量。
const data = svgSrc
  .replace(/^\s*\/\/.*$/gm, '')
  .replace(/window\.SVG_DATA\s*=/, 'const SVG_DATA =')
  .trim();

const banner = `// AUTO-GENERATED by build.mjs — do not edit.
// Commands: emoji (logic.part.js) | charts (charts.part.js) | dispatch (dispatch.part.js)
`;

const out = `${banner}${data}\n\n${logicSrc}\n\n${chartsSrc}\n\n${dispatchSrc}`;
writeFileSync(resolve(root, 'code.js'), out, 'utf8');

// 简单校验：语法 + 数据完整性
const entries = (out.match(/"(?:[A-Za-z]+Outlined)"/g) || []).length;
console.log(`Built code.js (${out.length} bytes, ${entries} icon refs). Run: node --check code.js`);